default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: pg32512
  host: localhost
  port: 5432
development:
  <<: *default
  database: tt-app_development
test:
  <<: *default
  database: tt-app_test
production:
  <<: *default
  database: tt-app_production
  username: dbrails
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  port: 5432
